[package]
name = "image_encryption"
version = "0.1.0"
authors = ["andrei"]
edition = "2021"

[dependencies]
clap = { version = "*", features = ["derive"] }
image = "*"
rand = { version = "*", features = ["small_rng"] }
